version: '3.8'

services:
  coordinator:
    build:
      context: .
      dockerfile: Dockerfile.coordinator
    ports:
      - "8000:8000"
    networks:
      - app_network



  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - app_network
    depends_on:
      - coordinator 

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    ports:
      - "8001:8001"
    networks:
      - app_network
    depends_on:
      - coordinator


    

networks:
  app_network:
    driver: bridge

volumes:
  rabbitmq_data:
