version: '3.8'

services:
  coordinator:
    build:
      context: .
      dockerfile: Dockerfile.coordinator
    ports:
      - "8000:8000"
    networks:
      - app_network
    depends_on:
      - rabbitmq 

  frontend:
  build:
    context: ./frontend
    dockerfile: Dockerfile
  ports:
    - "3000:80"
  networks:
    - app_network
  depends_on:
    - coordinator

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    ports:
      - "8001:8001"
    networks:
      - app_network
    depends_on:
      - rabbitmq
      - coordinator

  rabbitmq:
    image: rabbitmq:3.12-management  
    hostname: rabbitmq
    ports:
      - "5672:5672"  
      - "15672:15672"  
    environment:
      RABBITMQ_DEFAULT_USER: myuser  
      RABBITMQ_DEFAULT_PASS: mypassword  
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq 
    networks:
      - app_network


networks:
  app_network:
    driver: bridge

volumes:
  rabbitmq_data:  